### PR TITLE
Implement `SecKey<[u8]>` and `SecKey<str>`.

### PR DESCRIPTION
**Pull request by oblique**
Examples:

```rust
let mut unprotected = [1u8; 2];
let k = SecKey::from_bytes(&mut unprotected[..]).unwrap();

assert_eq!(unprotected, [0u8; 2]);
assert_eq!(*k.read(), [1u8; 2]);
```

```rust
let mut unprotected = "abc".to_string();
let k = SecKey::from_str(&mut unprotected).unwrap();

assert_eq!(&unprotected, "\0\0\0");
assert_eq!(&*k.read(), "abc");
```

### CODE REVIEW

**Comment by oblique** [comment]
CI fails because https://github.com/quininer/memsec/pull/10 is needed.

**Comment by oblique** [comment]
Do you prefer `SecKey::from_mut_u8` and `SecKey::from_mut_str` names instead?

**Comment by quininer** [comment]
I think we can implement `From` or `TryFrom` trait, just like Box?

**Comment by oblique** [comment]
With `TryFrom` I'm getting the following error:

```
    | impl<T: AsMut<[u8]>> TryFrom<T> for SecKey<[u8]> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: conflicting implementation in crate `core`:
            - impl<T, U> core::convert::TryFrom<U> for T
              where U: core::convert::Into<T>;
```

If I implement only `From` then it works, but we need to panic on failure, which I don't like.

In general you prefer the functions to take the ownership of the nonprotected data?
I can change the signatures to:

```rust
    pub fn from_bytes<T: AsMut<[u8]>>(mut src: T) -> Result<SecKey<[u8]>, T>;
    pub fn from_string(mut src: String) -> Result<SecKey<str>, String>;
```

**Comment by quininer** [comment]
I think it's good enough now, thanks.

**Pull request merged**
